# Generated by Django 6.0 on 2026-01-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_image_alter_course_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
