# Generated by Django 6.0 on 2026-01-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_student_student_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='course',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='course',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='course',
            new_name='lesson',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'lesson')},
        ),
    ]
